export enum RedisCacheKeys {
  GET_USER = 'GET_USER',
  LIST_USERS = 'LIST_USERS',
  AUTH_PASS = 'AUTH_PASS',
  LIMIT_REQUESTS = 'LIMIT_REQUESTS',
  VERIFY_USER = 'VERIFY_USER',
  GET_DESIGN = 'GET_DESIGN',
  LIST_DESIGNS = 'LIST_DESIGNS',
  GET_ORDER = 'GET_ORDER',
  LIST_ORDERS = 'LIST_ORDERS',
  GET_TRANSACTION = 'GET_TRANSACTION',
  LIST_TRANSACTIONS = 'LIST_TRANSACTIONS',
  GET_CART = 'GET_CART',
  GET_WALLET = 'GET_WALLET',
  GET_NOTIFICATION = 'GET_NOTIFICATION',
  LIST_NOTIFICATIONS = 'LIST_NOTIFICATIONS'
}
